### ISSUE TITLE
Attempting to use hooks causes "is not a function" error

### ISSUE THREAD

**Issue by jeffrimko** [mantinedev/next-app-template#14]
Not sure if I'm doing something wrong but the following results in an error:

1. Download latest template.
2. Install dependencies with `npm i`.
3. Start dev server with `npm run dev`, http://localhost:3000/ loads okay so far.
4. Attempting to use any hook causes the error. For example, editing `next-app-template-master/app/page.tsx` to the following will cause the error:
```tsx
import { Welcome } from '../components/Welcome/Welcome';
import { ColorSchemeToggle } from '../components/ColorSchemeToggle/ColorSchemeToggle';
import { useDisclosure } from '@mantine/hooks';   // Added this.

export default function HomePage() {
  const [opened, handlers] = useDisclosure(false);  // Added this, causes the error.

  return (
    <>
      <Welcome />
      <ColorSchemeToggle />
    </>
  );
}
```
The full text is the following: `Unhandled Runtime Error
Error: (0 , _barrel_optimize_names_useDisclosure_mantine_hooks__WEBPACK_IMPORTED_MODULE_3__.useDisclosure) is not a function or its return value is not iterable`

I've tried several hooks and they all result in the same issue. The output of `console.log(useDisclosure)` is `{}` for some reason.

I might be doing something wrong but couldn't find much info related to this error. Didn't see any documentation about getting hooks to work properly but maybe I missed it. 

My dev environment is the following:

- Windows 10 v22H2
- node v18.16.1
- npm 9.5.1

**Comment by rtivital** [comment]
Hooks can be used only in client components, add `'use client';` to the top of the file.

**Comment by jeffrimko** [comment]
Got it, thank you!
