### ISSUE TITLE
useDisclosure() causes runtime error

### ISSUE THREAD

**Issue by MikeSuiter** [mantinedev/next-app-template#19]
I'm working on an app started from this template and when I added useDisclosure() to it, I started getting this error.

```
Unhandled Runtime Error
Error: (0 , _barrel_optimize_names_useDisclosure_mantine_hooks__WEBPACK_IMPORTED_MODULE_1__.useDisclosure) is not a function or its return value is not iterable
```

After a lot of web searches I wasn't able to resolve it, so decided to try your current template and the same problem happens. I'm using pnpm but don't think that should matter. 

Change the beginning of Welcome.tsx to this and run.

```tsx
import { Title, Text, Anchor } from '@mantine/core';
import { useDisclosure } from '@mantine/hooks';
import classes from './Welcome.module.css';

export function Welcome() {
  const [opened, handlers] = useDisclosure(false, {
    onOpen: () => console.log('Opened'),
    onClose: () => console.log('Closed'),
  });

  console.log(opened);
  handlers.open();
  console.log(opened);

  return (
...
```

I updated Mantine and NextJS to the latest versions and still have the problem.

**Comment by rtivital** [comment]
You need to add `'use client';` to the top of the file to use hooks

**Comment by MikeSuiter** [comment]
Oh man, I got bit by this 3 weeks ago and funny thing this morning when I woke up it popped into my head why! First project using NextJS 14 (and Mantine) so I gotta get used to using 'use client' when needed.

Thanks and I'll close this.
