### ISSUE TITLE
Can't add font to fontFamily in global theme

### ISSUE THREAD

**Issue by mzavattaro** [mantinedev/next-app-template#21]
I've been trying to add a specific font `Jura, sans-serif` to the global theme `theme.ts`.

I followed this guide https://mantine.dev/theming/typography/ and it doesn't work with `Jura, sans-serif` from Google Fonts. It does correctly change the font to`Verdana, sans-serif` like in the example.

How do I get this to work:
```
'use client';

import { createTheme } from '@mantine/core';

export const theme = createTheme({
  /* Put your mantine theme override here */
  fontFamily: 'Jura, sans-serif',
});
```

Also, how do I get select components to have different fonts outside of those that are set in `theme.ts`? There doesn't seem to be an example having the `<Button />` have one font then the `<Input />` adopt a different font again.

Only thing I can think of is not having Mantine `theme.ts` manage the fonts and do the NextJS method of font management. Is that possible?

**Comment by rtivital** [comment]
https://codesandbox.io/s/beautiful-galois-tsy75q?file=/src/App.tsx

**Comment by mzavattaro** [comment]
Why doesn't it work in `theme.ts`?

**Comment by rtivital** [comment]
You did not include font files

```
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Jura&display=swap"
      rel="stylesheet"
    />
```

**Comment by mzavattaro** [comment]
That looks to have solved it. Is it possible to get this included in the https://mantine.dev/theming/typography/ section of the docs?

**Comment by prvnbist** [comment]
An alternative way as opposed to loading font scripts would be to use `next/font`.

```js
import { Jura} from 'next/font/google'

const jura = Inter({ subsets: ['latin'] })

export const theme = createTheme({
   fontFamily: jura.style.fontFamily
})
```

**Comment by rtivital** [comment]
https://help.mantine.dev/q/next-load-fonts
