### ISSUE TITLE
Permission to contribute

### ISSUE THREAD

**Issue by pedrocarlos-ti** [mantinedev/next-app-template#22]
Hello @rtivital 👋🏻 

I hope you're well. I'm Pedro Santos and I would like to contribute through PRs. 

Currently, I don't have the necessary permissions. 

Could you grant me access to submit PRs? I'm eager to contribute and willing to follow any guidelines you have.

By the way, not only I, but the rest of the community?

**Comment by rtivital** [comment]
I do not usually accept PRs to templates repos, if you are interested in contributing to the library, you can find a guide here – https://mantine.dev/contribute/

**Comment by pedrocarlos-ti** [comment]
Thank you @rtivital , I will definitely take a look there!!
