### ISSUE TITLE
Error: Hydration failed because the initial UI does not match what was rendered on the server.

### ISSUE THREAD

**Issue by hensansi** [mantinedev/next-app-template#7]
I was only able to reproduce this issue using cypress,

```
(uncaught exception)Error: Hydration failed because the initial UI does not match what was rendered on the server.
(uncaught exception)Error: Hydration failed because the initial UI does not match what was rendered on the server.
(uncaught exception)Error: Hydration failed because the initial UI does not match what was rendered on the server.

Warning: Expected server HTML to contain a matching <script> in <head>.

See more info here: https://nextjs.org/docs/messages/react-hydration-error
(uncaught exception)Error: Hydration failed because the initial UI does not match what was rendered on the server.

Warning: Expected server HTML to contain a matching <script> in <head>.

See more info here: https://nextjs.org/docs/messages/react-hydration-error
(uncaught exception)Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
```

Moving  `<ColorSchemeScript />` inside the body tag solves the issue but I have no idea if that is the correct solution.
Removing the `const metadata` solves the issue too but not ideal.

https://nextjs.org/docs/app/api-reference/components/script
https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration#step-3-migrating-nexthead

If needed I can try to create a basic cypress test to show the issue but it will take some time.

**Comment by sirPixieJerry** [comment]
I ran into the same problem today, but I am using Next.js v15 with React 19 and implemented Mantine in my own template. I used this template to look up things.

For any reason the `head` tag an `suppressHydrationWarning={true}` instead of just `suppressHydrationWarning` then the problem will disappear in dev but not after the build. I also don't know why because it doesn't make any sense to me.

Nevertheless the e2e tests after build would continue failing. Thanks to a [comment](https://github.com/cypress-io/cypress/issues/27204#issuecomment-1625490068) on another issue by the wonderful cypress team I found a solution.

Just wrap the `ColorSchemeScript` into a `Suspense`:

```ts
import '@mantine/core/styles.css';

import React, { Suspense } from 'react';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import { theme } from '../theme';

export const metadata = {
  title: 'Mantine Next.js template',
  description: 'I am using Mantine with Next.js!',
};

export default function RootLayout({ children }: { children: any }) {
  return (
    <html lang="en">
      <head>
        <Suspense>
          <ColorSchemeScript />
        </Suspense>
        <link rel="shortcut icon" href="/favicon.svg" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body>
        <MantineProvider theme={theme}>{children}</MantineProvider>
      </body>
    </html>
  );
}
```

For me this worked fine in dev and in the e2e tests.

**Comment by alvarocastro** [comment]
Hey @sirPixieJerry
I'm just starting a project with next.js 15 too and mantine, and your solution did nothing on my side, still getting the hydration error
![image](https://github.com/user-attachments/assets/71e8f97a-4a2b-410e-b5e5-7585afbe25b7)
It goes away if I just put the `suppressHydrationWarning` in the `<html>` tag, but I've never used it and feels bad to put it as "the solution".

**Comment by qhantom** [comment]
> It goes away if I just put the suppressHydrationWarning in the <html> tag, but I've never used it and feels bad to put it as "the solution".

Agree. Afaik it does suppress all hydration warnings even if they are legit, doesn't it?

**Comment by eraoul** [comment]
Same problem here.  I can also fix it by explicitly writing `data-mantine-color-scheme="light"` in the html tag, but that's clearly a hack.

**Comment by jayjay021** [comment]
upgrading to mantine v7.15 (released 4h ago) and adding ```<html  {...mantineHtmlProps}>``` solves the problem for me

**Comment by rtivital** [comment]
Yes, it has been updated in 7.15 release

**Comment by qhantom** [comment]
Thanks for your effort guys! 🙏  As I interpret the change, it still suppresses all hydration warnings even if they are legit, right? Would you mind sharing your thoughts on that change? Don't get me wrong, I do appreciate your work, I'm just curious. 🙂 Thanks!

**Comment by rtivital** [comment]
See https://github.com/mantinedev/mantine/issues/7008

**Comment by tophermurphy** [comment]
Posting the updated docs that fix the issue, for any other lost soul who found there way here.

`import { Head, Html, Main, NextScript } from 'next/document';
import { ColorSchemeScript, mantineHtmlProps } from '@mantine/core';

export default function Document() {
  return (
    <Html lang="en" {...mantineHtmlProps}>
      <Head>
        <ColorSchemeScript defaultColorScheme="auto" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}`
