### ISSUE TITLE
Adding components to layout.tsx has unexpected css compilation

### ISSUE THREAD

**Issue by prodigious-moustachio** [mantinedev/next-app-template#8]
When adding a component `Shell` to layout.tsx layout.css is compiled allowing mantine styling to override component styles e.g.,

```
.Shell-root {}
.mantine-styles {}
```

If I add the component to a page, then layout.css compiles with the expected specificity. Is this a bug or is there an approach that avoids this issue?

**Comment by rtivital** [comment]
It is a known issue of Next.js – https://github.com/vercel/next.js/issues/16630
On our side, it is planned to introduce separate bundles with css layers in next minor release.
